#!/bin/bash

#=================================================
# SOURCE HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	ynh_clean_check_starting
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC


#=================================================
# BOOK RESOURCES
#=================================================
ynh_script_progression --message="Booking resources for app..."


# --------------------
# Book install_dir
# --------------------
install_dir=/var/www/$app
test ! -e $install_dir || ynh_die "Directory $install_dir already exists."

# --------------------
# Book url
# --------------------
ynh_webpath_register $app $domain $path



#=================================================
# CUSTOM GLOBALS / TESTS
#=================================================

final_path=$install_dir
path_url=$path

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..."


ynh_app_setting_set --app=$app --key=is_public --value=$is_public
ynh_app_setting_set --app=$app --key=install_dir --value=$install_dir


#=================================================
# SOURCES
#=================================================
ynh_script_progression --message="sources..."

mkdir -p "$install_dir"
echo "Hello world!" > $install_dir/index.html

chown -R www-data: "$install_dir"
chmod -R 640 "$install_dir"
find "$install_dir" -type d -print0 | xargs -0 chmod 750

#=================================================
# CONF_NGINX
#=================================================
ynh_script_progression --message="conf_nginx..."

ynh_add_nginx_config

#=================================================
# CONF_SSOWAT
#=================================================
ynh_script_progression --message="conf_ssowat..."

[ $is_public -eq 0 ] || ynh_permission_update --permission "main" --add "visitors"
